sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
    packages:
      - cmake
      - cmake-data
      - g++-6


before_install:
  - mkdir Build
  - cd Build
  - cmake ..
  - cd ..

install:
  - export CXX="g++-6"
  - export CC="gcc-6"
  
script: 
  - g++-6 --version
  - cd Build
  - make
  - cd ..
